title: Alex de Beer
email: adeb970@aucklanduni.ac.nz
description: 
url: "" # the base hostname & protocol for your site, e.g. http://example.com

curriculum: 
  name: cv
  url: "assets/cv.pdf"
github_url: https://github.com/alexgdebeer
linkedin_url: https://linkedin.com/in/alexgdebeer
googlescholar_url: https://scholar.google.com/citations?user=BRtTbsEAAAAJ&hl=en

# Build settings
# remote_theme: gaalcaras/academic
plugins:
  - jekyll-feed
#   - jekyll-seo-tag

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
